# =================================
# = Spring
# =================================
spring:
  datasource:
    url: jdbc:mysql://db-realmeet.cu4i8wlghyu4.sa-east-1.rds.amazonaws.com:3306/realmeet?&serverTimezone=UTC&useSSL=false
    username: admin