# =============================
# = Spring
# =============================
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-3-232-163-23.compute-1.amazonaws.com:5432/ders3sc31g3kvv
    username: cbdirlyvprbyfm
  flyway:
    locations: classpath:/db/migration/postgresql